# ==========================
# Fleet 1 Nav2 Configuration
# ==========================


# --------------------------
# Lifecycle Manager
# --------------------------
lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - /fleet_2/controller_server
      - /fleet_2/smoother_server
      - /fleet_2/planner_server
      - /fleet_2/behavior_server
      - /fleet_2/bt_navigator
      - /fleet_2/waypoint_follower
      - /fleet_2/velocity_smoother   

# --------------------------
# Controller Server
# --------------------------
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    global_frame: map
    robot_base_frame: fleet_2/base_link
    odom_topic: fleet_2/odometry      

    # Progress checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal checker
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    # DWB Local Planner
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      debug_trajectory_details: true
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: true
      limit_vel_cmd_in_traj: false
      stateful: true

      # Critic definitions
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoal"
        scale: 32.0
        slowing_factor: 5.0
        lookahead_time: -1.0

      Oscillation:
        plugin: "dwb_critics::Oscillation"
        scale: 1.0
        oscillation_reset_dist: 0.05
        oscillation_reset_angle: 0.2
        oscillation_reset_time: -1.0
        x_only_threshold: 0.05

      BaseObstacle:
        plugin: "dwb_critics::BaseObstacle"
        scale: 0.02
        sum_scores: false

      GoalAlign:
        plugin: "dwb_critics::GoalAlign"
        scale: 24.0
        forward_point_distance: 0.1

      PathAlign:
        plugin: "dwb_critics::PathAlign"
        scale: 32.0
        forward_point_distance: 0.1

      PathDist:
        plugin: "dwb_critics::PathDist"
        scale: 32.0

      GoalDist:
        plugin: "dwb_critics::GoalDist"
        scale: 24.0

# --------------------------
# Planner Server
# --------------------------
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    global_frame: map
    robot_base_frame: fleet_2/base_link
    odom_frame: fleet_2/base_link

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5

# --------------------------
# Behavior Tree Navigator
# --------------------------
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: fleet_2/base_link
    odom_topic: fleet_2/odometry
    goal_pose_topic: /fleet_2/goal_pose
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: "~/ros_jazzy_ws/src/navigation/fleet_navigation_bringup/behavior_trees/fleet_2_navigate_to_pose.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_recovery_node_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node

# --------------------------
# Waypoint Follower
# --------------------------
waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 200

# --------------------------
# Global Costmap
# --------------------------
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: fleet_2/base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.2
      width: 100
      height: 100
      origin_x: -50.0
      origin_y: -50.0
      rolling_window: false
      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "traversability_global_occupancygrid"
        subscribe_to_updates: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

# --------------------------
# Local Costmap
# --------------------------
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: fleet_2/base_link
      robot_base_frame: fleet_2/base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.2
      width: 10
      height: 10
      origin_x: -5.0
      origin_y: -5.0
      rolling_window: true
      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "traversability_occupancygrid"
        subscribe_to_updates: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
